/**
 * F9 — the weekly insights feed. One component, four honest states:
 *   - free tier      → a hand-written SAMPLE insight + upsell to Plus (the
 *                      preview is never model-generated, per the shared const).
 *   - Plus+, opted out → a gentle note + link to turn insights on in settings.
 *   - Plus+, no insight yet → "your first reflection arrives this Sunday".
 *   - Plus+, has insights → the real feed.
 *
 * Insights are generated by the Sunday cron, never on demand — there is no
 * "generate now" button (a user can't spend a Sonnet call by tapping).
 */
import { Link, useParams } from "react-router";
import { ArrowRight, Sparkles } from "lucide-react";
import { SUKOON_SAMPLE_INSIGHT, type SukoonInsight } from "@neev/shared";
import { Button } from "@/components/ui/button";
import { SectionCard } from "@/components/ui-x/section-card";
import { cn } from "@/lib/utils";
import { useSukoonLanguage } from "@/sukoon/lib/use-sukoon-language";
import { useInsights } from "@/sukoon/lib/use-sukoon-insights";

export function InsightsFeed({ max }: { max?: number }) {
  const { t, language } = useSukoonLanguage();
  const { locale } = useParams<{ locale?: string }>();
  const base = locale ? `/${locale}/sukoon` : "";
  const query = useInsights();

  if (query.isPending) return <div className="h-40 animate-pulse rounded-2xl bg-muted" />;
  if (!query.data) return null;

  const { insights, tier, enabled } = query.data;

  // Free tier → sample + upsell.
  if (tier === "free") {
    return (
      <SectionCard
        title={
          <span className="flex items-center gap-2">
            <Sparkles className="size-4 text-secondary" aria-hidden />
            {t("Sukoon.insights.title")}
          </span>
        }
        description={t("Sukoon.insights.upsellSub")}
      >
        <div className="flex flex-col gap-3">
          <div className="rounded-xl border border-dashed border-secondary/40 bg-secondary/5 p-4">
            <p className="mb-2 text-[11px] font-medium uppercase tracking-wide text-secondary">
              {t("Sukoon.insights.sampleBadge")}
            </p>
            <p className="text-sm leading-relaxed text-foreground">
              {language === "hi" ? SUKOON_SAMPLE_INSIGHT.summary_hi : SUKOON_SAMPLE_INSIGHT.summary_en}
            </p>
            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              <span className="font-medium text-foreground">{t("Sukoon.insights.suggestionLabel")}: </span>
              {language === "hi" ? SUKOON_SAMPLE_INSIGHT.suggestion_hi : SUKOON_SAMPLE_INSIGHT.suggestion_en}
            </p>
          </div>
          <Button asChild size="sm" className="self-start">
            <Link to={`${base}/pricing`}>
              {t("Sukoon.insights.upsellCta")}
              <ArrowRight className="size-3.5" aria-hidden />
            </Link>
          </Button>
        </div>
      </SectionCard>
    );
  }

  // Plus+, but insights turned off in settings.
  if (!enabled) {
    return (
      <SectionCard title={t("Sukoon.insights.title")}>
        <div className="flex flex-col gap-2">
          <p className="text-sm text-muted-foreground">{t("Sukoon.insights.optedOut")}</p>
          <Button asChild size="sm" variant="outline" className="self-start">
            <Link to={`${base}/you`}>{t("Sukoon.insights.turnOn")}</Link>
          </Button>
        </div>
      </SectionCard>
    );
  }

  // Plus+, enabled, no insight yet.
  if (insights.length === 0) {
    return (
      <SectionCard
        title={
          <span className="flex items-center gap-2">
            <Sparkles className="size-4 text-secondary" aria-hidden />
            {t("Sukoon.insights.title")}
          </span>
        }
      >
        <p className="text-sm leading-relaxed text-muted-foreground">{t("Sukoon.insights.pending")}</p>
      </SectionCard>
    );
  }

  const shown = max ? insights.slice(0, max) : insights;
  return (
    <SectionCard
      title={
        <span className="flex items-center gap-2">
          <Sparkles className="size-4 text-secondary" aria-hidden />
          {t("Sukoon.insights.title")}
        </span>
      }
      description={t("Sukoon.insights.feedSub")}
    >
      <div className="flex flex-col gap-4">
        {shown.map((insight) => (
          <InsightCard key={insight.id} insight={insight} base={base} />
        ))}
      </div>
    </SectionCard>
  );
}

function InsightCard({ insight, base }: { insight: SukoonInsight; base: string }) {
  const { t, language } = useSukoonLanguage();
  const weekLabel = new Date(`${insight.week_start}T00:00:00`).toLocaleDateString(
    language === "hi" ? "hi-IN" : "en-IN",
    { day: "numeric", month: "long", year: "numeric" },
  );
  const journeyTitle = language === "hi" ? insight.journey_title_hi : insight.journey_title_en;

  return (
    <article className="rounded-xl border border-border bg-card p-4" lang={language}>
      <p className="mb-2 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
        {t("Sukoon.insights.weekOf", { date: weekLabel })}
      </p>
      <p className="text-sm leading-relaxed text-foreground">{insight.content.summary}</p>

      {insight.content.suggestion ? (
        <p className="mt-3 rounded-lg bg-secondary/10 px-3 py-2 text-sm leading-relaxed text-foreground">
          <span className="font-medium">{t("Sukoon.insights.suggestionLabel")}: </span>
          {insight.content.suggestion}
        </p>
      ) : null}

      {insight.content.journey_slug && journeyTitle ? (
        <Link
          to={`${base}/journeys/${insight.content.journey_slug}`}
          className={cn(
            "mt-3 flex items-center justify-between gap-2 rounded-lg border border-secondary/30 bg-secondary/5 px-3 py-2",
            "text-sm text-foreground transition-colors duration-300 hover:border-secondary/60",
          )}
        >
          <span>
            <span className="text-xs text-muted-foreground">{t("Sukoon.insights.journeyLabel")}</span>
            <br />
            <span className="font-medium">{journeyTitle}</span>
          </span>
          <ArrowRight className="size-4 shrink-0 text-secondary" aria-hidden />
        </Link>
      ) : null}
    </article>
  );
}
