/**
 * The VERBATIM official UPSC Civil Services Examination syllabus text — one entry
 * per printed bullet/line. This array is the ground truth the coverage verifier
 * gates against: every line here must be claimed by >=1 node in
 * `upsc-syllabus-tree.ts` (nothing missed), and every node must cover >=1 line
 * somewhere in its subtree (nothing invented).
 *
 * ── SOURCE DOCUMENTS (exact) ────────────────────────────────────────────────
 * PRIMARY (every line below was read from this document):
 *   https://www.upsc.gov.in/sites/default/files/Notif-CSP-2026-Engl-060226Rev.pdf
 *   "EXAMINATION NOTICE NO 05/2026-CSE", dated 04.02.2026.
 *   Prelims syllabus: Section III, Part A. Mains syllabus: pp. 33-35.
 *
 * UPSC PUBLISHES NO STANDALONE CSE SYLLABUS DOCUMENT. `/examinations/
 * revised-syllabus-scheme` carries only Geo-Scientist 2020 and CMS 2018 — the
 * ANNUAL EXAMINATION NOTICE *is* the syllabus of record. Do not go hunting for
 * a syllabus-only PDF; there isn't one.
 *
 * STABILITY: all 75 lines are byte-identical across the official 2026, 2025,
 * 2024 and 2022 notifications — the CSE syllabus text has not changed since at
 * least 2022. Cross-verification copy (also registered in content-sources.yaml):
 *   https://www.upsc.gov.in/sites/default/files/Notif-CSP-2025-Engl-220125.pdf
 *
 * ── TWO TRAPS, BOTH HIT DURING SOURCING ─────────────────────────────────────
 * 1. The `www.` prefix is MANDATORY for `sites/default/files` PDFs. The bare
 *    `upsc.gov.in` host returns HTTP 200 with `text/html` soft-404 content, so
 *    the failure MASQUERADES AS SUCCESS — a naive status-code check passes.
 * 2. `upsc.gov.in/sites/default/files/GENERAL STUDIES-III.pdf` is NOT the
 *    syllabus. It is the CSE Mains 2014 QUESTION PAPER.
 *
 * ── OFFICIAL TYPOS AND QUIRKS ARE PRESERVED VERBATIM, BY DESIGN ─────────────
 * The official text contains ~20 typographical defects and inconsistencies:
 * `mobilization, of resources`, `Ethics in-human actions`, `irrigation systems
 * storage`, `location-changes`, `Geography-Physical`, `scope' and significance`,
 * `weaker-sections`, `System- objectives`, `family society and`, an
 * ungrammatical `organs` clause (GS2-L03), mixed ASCII-hyphen/en-dash/em-dash
 * forms, and lowercase `literature` / `Environmental ecology`. These are in the
 * commission's own document. DO NOT "FIX" THEM — byte-fidelity is the audit
 * trail, and every third-party reproduction checked silently normalised at
 * least one of them (which is exactly why none was used as a source).
 *
 * Also deliberately NOT recorded as official: the number of questions per
 * prelims paper. The notification fixes only 200 marks and two hours per paper;
 * the familiar 100/80 figures are observed from past papers, not notified. This
 * matches migration 0106's `question_count: null` for UPSC.
 */
import type { OfficialSyllabusLine } from "./upsc-syllabus-types.js";

export const UPSC_OFFICIAL_LINES: OfficialSyllabusLine[] = [
  // ── UPSC_PRE_GS1 ──
  { id: "P1-L01", paperCode: "UPSC_PRE_GS1", text: "Current events of national and international importance.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Section III Part A, Paper I bullet 1" },
  { id: "P1-L02", paperCode: "UPSC_PRE_GS1", text: "History of India and Indian National Movement.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Section III Part A, Paper I bullet 2" },
  { id: "P1-L03", paperCode: "UPSC_PRE_GS1", text: "Indian and World Geography-Physical, Social, Economic Geography of India and the World.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Section III Part A, Paper I bullet 3" },
  { id: "P1-L04", paperCode: "UPSC_PRE_GS1", text: "Indian Polity and Governance-Constitution, Political System, Panchayati Raj, Public Policy, Rights Issues, etc.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Section III Part A, Paper I bullet 4" },
  { id: "P1-L05", paperCode: "UPSC_PRE_GS1", text: "Economic and Social Development-Sustainable Development, Poverty, Inclusion, Demographics, Social Sector Initiatives, etc.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Section III Part A, Paper I bullet 5" },
  { id: "P1-L06", paperCode: "UPSC_PRE_GS1", text: "General issues on Environmental ecology, Bio-diversity and Climate Change - that do not require subject specialization.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Section III Part A, Paper I bullet 6" },
  { id: "P1-L07", paperCode: "UPSC_PRE_GS1", text: "General Science.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Section III Part A, Paper I bullet 7" },
  // ── UPSC_PRE_CSAT ──
  { id: "P2-L01", paperCode: "UPSC_PRE_CSAT", text: "Comprehension;", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Section III Part A, Paper II bullet 1" },
  { id: "P2-L02", paperCode: "UPSC_PRE_CSAT", text: "Interpersonal skills including communication skills;", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Section III Part A, Paper II bullet 2" },
  { id: "P2-L03", paperCode: "UPSC_PRE_CSAT", text: "Logical reasoning and analytical ability;", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Section III Part A, Paper II bullet 3" },
  { id: "P2-L04", paperCode: "UPSC_PRE_CSAT", text: "Decision making and problem solving;", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Section III Part A, Paper II bullet 4" },
  { id: "P2-L05", paperCode: "UPSC_PRE_CSAT", text: "General mental ability;", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Section III Part A, Paper II bullet 5" },
  { id: "P2-L06", paperCode: "UPSC_PRE_CSAT", text: "Basic numeracy (numbers and their relations, orders of magnitude, etc.) (Class X level), Data interpretation (charts, graphs, tables, data sufficiency etc. — Class X level);", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Section III Part A, Paper II bullet 6" },
  // ── UPSC_MAINS_ESSAY ──
  { id: "ESSAY-L01", paperCode: "UPSC_MAINS_ESSAY", text: "Essay: Candidates may be required to write essays on multiple topics. They will be expected to keep closely to the subject of the essay to arrange their ideas in orderly fashion, and to write concisely. Credit will be given for effective and exact expression.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-I (Essay), single unbulleted paragraph (page 33)" },
  // ── UPSC_MAINS_GS1 ──
  { id: "GS1-L01", paperCode: "UPSC_MAINS_GS1", text: "Indian culture will cover the salient aspects of Art Forms, literature and Architecture from ancient to modern times.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-II (General Studies-I), p.33, bullet 1" },
  { id: "GS1-L02", paperCode: "UPSC_MAINS_GS1", text: "Modern Indian history from about the middle of the eighteenth century until the present- significant events, personalities, issues.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-II (General Studies-I), p.33, bullet 2" },
  { id: "GS1-L03", paperCode: "UPSC_MAINS_GS1", text: "The Freedom Struggle — its various stages and important contributors/contributions from different parts of the country.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-II (General Studies-I), p.33, bullet 3" },
  { id: "GS1-L04", paperCode: "UPSC_MAINS_GS1", text: "Post-independence consolidation and reorganization within the country.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-II (General Studies-I), p.33, bullet 4" },
  { id: "GS1-L05", paperCode: "UPSC_MAINS_GS1", text: "History of the world will include events from 18th century such as industrial revolution, world wars, redrawal of national boundaries, colonization, decolonization, political philosophies like communism, capitalism, socialism etc.— their forms and effect on the society.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-II (General Studies-I), p.33, bullet 5" },
  { id: "GS1-L06", paperCode: "UPSC_MAINS_GS1", text: "Salient features of Indian Society, Diversity of India.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-II (General Studies-I), p.33, bullet 6" },
  { id: "GS1-L07", paperCode: "UPSC_MAINS_GS1", text: "Role of women and women’s organization, population and associated issues, poverty and developmental issues, urbanization, their problems and their remedies.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-II (General Studies-I), p.33, bullet 7" },
  { id: "GS1-L08", paperCode: "UPSC_MAINS_GS1", text: "Effects of globalization on Indian society.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-II (General Studies-I), p.33, bullet 8" },
  { id: "GS1-L09", paperCode: "UPSC_MAINS_GS1", text: "Social empowerment, communalism, regionalism & secularism.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-II (General Studies-I), p.33, bullet 9" },
  { id: "GS1-L10", paperCode: "UPSC_MAINS_GS1", text: "Salient features of world’s physical geography.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-II (General Studies-I), p.33, bullet 10" },
  { id: "GS1-L11", paperCode: "UPSC_MAINS_GS1", text: "Distribution of key natural resources across the world (including South Asia and the Indian sub-continent); factors responsible for the location of primary, secondary, and tertiary sector industries in various parts of the world (including India).", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-II (General Studies-I), p.33, bullet 11" },
  { id: "GS1-L12", paperCode: "UPSC_MAINS_GS1", text: "Important Geophysical phenomena such as earthquakes, Tsunami, Volcanic activity, cyclone etc., geographical features and their location-changes in critical geographical features (including water-bodies and ice-caps) and in flora and fauna and the effects of such changes.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-II (General Studies-I), p.33, bullet 12" },
  // ── UPSC_MAINS_GS2 ──
  { id: "GS2-L01", paperCode: "UPSC_MAINS_GS2", text: "Indian Constitution—historical underpinnings, evolution, features, amendments, significant provisions and basic structure.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 1" },
  { id: "GS2-L02", paperCode: "UPSC_MAINS_GS2", text: "Functions and responsibilities of the Union and the States, issues and challenges pertaining to the federal structure, devolution of powers and finances up to local levels and challenges therein.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 2" },
  { id: "GS2-L03", paperCode: "UPSC_MAINS_GS2", text: "Separation of powers between various organs dispute redressal mechanisms and institutions.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 3" },
  { id: "GS2-L04", paperCode: "UPSC_MAINS_GS2", text: "Comparison of the Indian constitutional scheme with that of other countries.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 4" },
  { id: "GS2-L05", paperCode: "UPSC_MAINS_GS2", text: "Parliament and State legislatures—structure, functioning, conduct of business, powers & privileges and issues arising out of these.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 5" },
  { id: "GS2-L06", paperCode: "UPSC_MAINS_GS2", text: "Structure, organization and functioning of the Executive and the Judiciary—Ministries and Departments of the Government; pressure groups and formal/informal associations and their role in the Polity.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 6" },
  { id: "GS2-L07", paperCode: "UPSC_MAINS_GS2", text: "Salient features of the Representation of People’s Act.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 7" },
  { id: "GS2-L08", paperCode: "UPSC_MAINS_GS2", text: "Appointment to various Constitutional posts, powers, functions and responsibilities of various Constitutional Bodies.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 8" },
  { id: "GS2-L09", paperCode: "UPSC_MAINS_GS2", text: "Statutory, regulatory and various quasi-judicial bodies.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 9" },
  { id: "GS2-L10", paperCode: "UPSC_MAINS_GS2", text: "Government policies and interventions for development in various sectors and issues arising out of their design and implementation.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 10" },
  { id: "GS2-L11", paperCode: "UPSC_MAINS_GS2", text: "Development processes and the development industry —the role of NGOs, SHGs, various groups and associations, donors, charities, institutional and other stakeholders.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 11" },
  { id: "GS2-L12", paperCode: "UPSC_MAINS_GS2", text: "Welfare schemes for vulnerable sections of the population by the Centre and States and the performance of these schemes; mechanisms, laws, institutions and Bodies constituted for the protection and betterment of these vulnerable sections.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 12" },
  { id: "GS2-L13", paperCode: "UPSC_MAINS_GS2", text: "Issues relating to development and management of Social Sector/Services relating to Health, Education, Human Resources.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 13" },
  { id: "GS2-L14", paperCode: "UPSC_MAINS_GS2", text: "Issues relating to poverty and hunger.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 14" },
  { id: "GS2-L15", paperCode: "UPSC_MAINS_GS2", text: "Important aspects of governance, transparency and accountability, e-governance- applications, models, successes, limitations, and potential; citizens charters, transparency & accountability and institutional and other measures.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 15" },
  { id: "GS2-L16", paperCode: "UPSC_MAINS_GS2", text: "Role of civil services in a democracy.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 16" },
  { id: "GS2-L17", paperCode: "UPSC_MAINS_GS2", text: "India and its neighborhood- relations.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 17" },
  { id: "GS2-L18", paperCode: "UPSC_MAINS_GS2", text: "Bilateral, regional and global groupings and agreements involving India and/or affecting India’s interests.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 18" },
  { id: "GS2-L19", paperCode: "UPSC_MAINS_GS2", text: "Effect of policies and politics of developed and developing countries on India’s interests, Indian diaspora.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 19" },
  { id: "GS2-L20", paperCode: "UPSC_MAINS_GS2", text: "Important International institutions, agencies and fora- their structure, mandate.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, EXAMINATION NOTICE NO 05/2026-CSE, Mains Paper-III (General Studies- II), p.34-35, bullet 20" },
  // ── UPSC_MAINS_GS3 ──
  { id: "GS3-L01", paperCode: "UPSC_MAINS_GS3", text: "Indian Economy and issues relating to planning, mobilization, of resources, growth, development and employment.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 1" },
  { id: "GS3-L02", paperCode: "UPSC_MAINS_GS3", text: "Inclusive growth and issues arising from it.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 2" },
  { id: "GS3-L03", paperCode: "UPSC_MAINS_GS3", text: "Government Budgeting.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 3" },
  { id: "GS3-L04", paperCode: "UPSC_MAINS_GS3", text: "Major crops-cropping patterns in various parts of the country, - different types of irrigation and irrigation systems storage, transport and marketing of agricultural produce and issues and related constraints; e-technology in the aid of farmers.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 4" },
  { id: "GS3-L05", paperCode: "UPSC_MAINS_GS3", text: "Issues related to direct and indirect farm subsidies and minimum support prices; Public Distribution System- objectives, functioning, limitations, revamping; issues of buffer stocks and food security; Technology missions; economics of animal-rearing.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 5" },
  { id: "GS3-L06", paperCode: "UPSC_MAINS_GS3", text: "Food processing and related industries in India- scope’ and significance, location, upstream and downstream requirements, supply chain management.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 6" },
  { id: "GS3-L07", paperCode: "UPSC_MAINS_GS3", text: "Land reforms in India.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 7" },
  { id: "GS3-L08", paperCode: "UPSC_MAINS_GS3", text: "Effects of liberalization on the economy, changes in industrial policy and their effects on industrial growth.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 8" },
  { id: "GS3-L09", paperCode: "UPSC_MAINS_GS3", text: "Infrastructure: Energy, Ports, Roads, Airports, Railways etc.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 9" },
  { id: "GS3-L10", paperCode: "UPSC_MAINS_GS3", text: "Investment models.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 10" },
  { id: "GS3-L11", paperCode: "UPSC_MAINS_GS3", text: "Science and Technology- developments and their applications and effects in everyday life.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 11" },
  { id: "GS3-L12", paperCode: "UPSC_MAINS_GS3", text: "Achievements of Indians in science & technology; indigenization of technology and developing new technology.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 12" },
  { id: "GS3-L13", paperCode: "UPSC_MAINS_GS3", text: "Awareness in the fields of IT, Space, Computers, robotics, nano-technology, bio-technology and issues relating to intellectual property rights.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 13" },
  { id: "GS3-L14", paperCode: "UPSC_MAINS_GS3", text: "Conservation, environmental pollution and degradation, environmental impact assessment.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 14" },
  { id: "GS3-L15", paperCode: "UPSC_MAINS_GS3", text: "Disaster and disaster management.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 15" },
  { id: "GS3-L16", paperCode: "UPSC_MAINS_GS3", text: "Linkages between development and spread of extremism.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 16" },
  { id: "GS3-L17", paperCode: "UPSC_MAINS_GS3", text: "Role of external state and non-state actors in creating challenges to internal security.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 17" },
  { id: "GS3-L18", paperCode: "UPSC_MAINS_GS3", text: "Challenges to internal security through communication networks, role of media and social networking sites in internal security challenges, basics of cyber security; money-laundering and its prevention.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 18" },
  { id: "GS3-L19", paperCode: "UPSC_MAINS_GS3", text: "Security challenges and their management in border areas - linkages of organized crime with terrorism.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 19" },
  { id: "GS3-L20", paperCode: "UPSC_MAINS_GS3", text: "Various Security forces and agencies and their mandate.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-IV (General Studies-III), bullet 20" },
  // ── UPSC_MAINS_GS4 ──
  { id: "GS4-L01", paperCode: "UPSC_MAINS_GS4", text: "This paper will include questions to test the candidates’ attitude and approach to issues relating to integrity, probity in public life and his problem solving approach to various issues and conflicts faced by him in dealing with society. Questions may utilise the case study approach to determine these aspects. The following broad areas will be covered:", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-V (General Studies-IV), bullet 1 (preamble bullet; ends 'The following broad areas will be covered:')" },
  { id: "GS4-L02", paperCode: "UPSC_MAINS_GS4", text: "Ethics and Human Interface: Essence, determinants and consequences of Ethics in-human actions; dimensions of ethics; ethics - in private and public relationships. Human Values - lessons from the lives and teachings of great leaders, reformers and administrators; role of family society and educational institutions in inculcating values.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-V (General Studies-IV), bullet 2" },
  { id: "GS4-L03", paperCode: "UPSC_MAINS_GS4", text: "Attitude: content, structure, function; its influence and relation with thought and behaviour; moral and political attitudes; social influence and persuasion.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-V (General Studies-IV), bullet 3" },
  { id: "GS4-L04", paperCode: "UPSC_MAINS_GS4", text: "Aptitude and foundational values for Civil Service, integrity, impartiality and non-partisanship, objectivity, dedication to public service, empathy, tolerance and compassion towards the weaker-sections.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-V (General Studies-IV), bullet 4" },
  { id: "GS4-L05", paperCode: "UPSC_MAINS_GS4", text: "Emotional intelligence-concepts, and their utilities and application in administration and governance.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-V (General Studies-IV), bullet 5" },
  { id: "GS4-L06", paperCode: "UPSC_MAINS_GS4", text: "Contributions of moral thinkers and philosophers from India and world.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-V (General Studies-IV), bullet 6" },
  { id: "GS4-L07", paperCode: "UPSC_MAINS_GS4", text: "Public/Civil service values and Ethics in Public administration: Status and problems; ethical concerns and dilemmas in government and private institutions; laws, rules, regulations and conscience as sources of ethical guidance; accountability and ethical governance; strengthening of ethical and moral values in governance; ethical issues in international relations and funding; corporate governance.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-V (General Studies-IV), bullet 7" },
  { id: "GS4-L08", paperCode: "UPSC_MAINS_GS4", text: "Probity in Governance: Concept of public service; Philosophical basis of governance and probity; Information sharing and transparency in government, Right to Information, Codes of Ethics, Codes of Conduct, Citizen’s Charters, Work culture, Quality of service delivery, Utilization of public funds, challenges of corruption.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-V (General Studies-IV), bullet 8" },
  { id: "GS4-L09", paperCode: "UPSC_MAINS_GS4", text: "Case Studies on above issues.", source: "Notif-CSP-2026-Engl-060226Rev.pdf, Examination Notice No 05/2026-CSE, Mains Paper-V (General Studies-IV), bullet 9 (case-study bullet)" },
];
