import type { CrisisKeywordList } from "./types.js";

/**
 * Romanized Hindi (Hinglish) — how most aspirants actually type distress on a
 * phone. Covers transliteration variants (atmahatya / aatmhatya / atma hatya)
 * and common misspellings. Matched case-insensitively on word boundaries.
 *
 * REVIEWER NOTE (SUKOON_CONTEXT): human-reviewed list. The famous false-positive
 * to protect against — "main theek hoon, suicide jokes mat karo" — is handled by
 * the suppressors below (theek hoon + jokes + mat karo), NOT by weakening the
 * real self-harm phrases.
 */
export const hinglishKeywords: CrisisKeywordList = {
  strong: [
    // critical — first-person intent
    { pattern: "marna chahta hoon", level: "critical" },
    { pattern: "marna chahti hoon", level: "critical" },
    { pattern: "marna chahta hun", level: "critical" },
    { pattern: "marna chahti hun", level: "critical" },
    { pattern: "mai marna chahta", level: "critical" },
    { pattern: "main marna chahta", level: "critical" },
    { pattern: "mar jana chahta", level: "critical" },
    { pattern: "mar jana chahti", level: "critical" },
    { pattern: "mar jaana chahta", level: "critical" },
    { pattern: "jeena nahi chahta", level: "critical" },
    { pattern: "jeena nahi chahti", level: "critical" },
    { pattern: "jina nahi chahta", level: "critical" },
    { pattern: "jeena nhi chahta", level: "critical" },
    { pattern: "jeene ka mann nahi", level: "critical" },
    { pattern: "jeene ka man nahi", level: "critical" },
    { pattern: "ab jeena nahi", level: "critical" },
    { pattern: "jaan de dunga", level: "critical" },
    { pattern: "jaan de dungi", level: "critical" },
    { pattern: "jaan dena chahta", level: "critical" },
    { pattern: "apni jaan de", level: "critical" },
    { pattern: "khudkushi karunga", level: "critical" },
    { pattern: "khudkushi karungi", level: "critical" },
    { pattern: "khud kushi karunga", level: "critical" },
    { pattern: "atmahatya karunga", level: "critical" },
    { pattern: "atmahatya kar lunga", level: "critical" },
    { pattern: "khud ko mar", level: "critical" },
    { pattern: "khud ko khatam kar", level: "critical" },
    { pattern: "sab khatam kar dunga", level: "critical" },
    { pattern: "sab khatam kar dun", level: "critical" },
    { pattern: "zindagi khatam kar", level: "critical" },
    { pattern: "zindagi khatm kar", level: "critical" },
    { pattern: "phansi laga", level: "critical" },
    { pattern: "phaasi laga", level: "critical" },
    { pattern: "neend ki goli kha", level: "critical" },
    // high — passive death wish / self-injury
    { pattern: "marne ka mann", level: "high" },
    { pattern: "marne ka man kar", level: "high" },
    { pattern: "mar jaun", level: "high" },
    { pattern: "kaash mar jaun", level: "high" },
    { pattern: "khud ko nuksan", level: "high" },
    { pattern: "khud ko chot", level: "high" },
    { pattern: "mere bina sab behtar", level: "high" },
    { pattern: "mere bina sab better", level: "high" },
    { pattern: "kisi ko farak nahi padega", level: "high" },
    { pattern: "kisi ko fark nahi padega", level: "high" },
    { pattern: "mar jau to accha", level: "high" },
    { pattern: "mar jau to behtar", level: "high" },
    // moderate — hopelessness / breakdown / exam-despair
    { pattern: "toot gaya hoon", level: "moderate" },
    { pattern: "toot gayi hoon", level: "moderate" },
    { pattern: "toot chuka hoon", level: "moderate" },
    { pattern: "bikhar gaya hoon", level: "moderate" },
    { pattern: "bahut akela hoon", level: "moderate" },
    { pattern: "bahut akeli hoon", level: "moderate" },
    { pattern: "koi umeed nahi", level: "moderate" },
    { pattern: "koi ummid nahi", level: "moderate" },
    { pattern: "umeed khatam", level: "moderate" },
    { pattern: "bekaar hoon", level: "moderate" },
    { pattern: "bekar hoon", level: "moderate" },
    { pattern: "kisi kaam ka nahi", level: "moderate" },
    { pattern: "kisi kaam ki nahi", level: "moderate" },
    { pattern: "haar gaya hoon", level: "moderate" },
    { pattern: "haar gayi hoon", level: "moderate" },
    { pattern: "ab aur nahi ho payega", level: "moderate" },
    { pattern: "ab aur nahi hota", level: "moderate" },
    { pattern: "bardaasht nahi ho raha", level: "moderate" },
    { pattern: "bardasht nahi ho raha", level: "moderate" },
    { pattern: "ghut raha hoon", level: "moderate" },
    { pattern: "ro raha hoon din bhar", level: "moderate" },
    { pattern: "zindagi bekar", level: "moderate" },
    { pattern: "life barbaad", level: "moderate" },
    { pattern: "sab barbaad ho gaya", level: "moderate" },
    { pattern: "career khatam", level: "moderate" },
    { pattern: "career khatm", level: "moderate" },
  ],
  weak: [
    { pattern: "suicide", level: "high" },
    { pattern: "khudkushi", level: "high" },
    { pattern: "khud kushi", level: "high" },
    { pattern: "khudkhushi", level: "high" },
    { pattern: "atmahatya", level: "high" },
    { pattern: "aatmhatya", level: "high" },
    { pattern: "atma hatya", level: "high" },
    { pattern: "sucide", level: "high" }, // misspelling
    { pattern: "suiside", level: "high" }, // misspelling
    { pattern: "sewiside", level: "high" }, // phonetic misspelling
    // mild distress → low (never suppressed by topical markers; see detector)
    { pattern: "bahut tension", level: "low" },
    { pattern: "bohot tension", level: "low" },
    { pattern: "bahut stress", level: "low" },
    { pattern: "bahut pareshan", level: "low" },
    { pattern: "ghabrahat ho rahi", level: "low" },
    { pattern: "dar lag raha", level: "low" },
    { pattern: "neend nahi aa rahi", level: "low" },
    { pattern: "thak gaya hoon", level: "low" },
    { pattern: "thak gayi hoon", level: "low" },
    { pattern: "pressure bahut", level: "low" },
    { pattern: "dimaag nahi chal raha", level: "low" },
  ],
  suppressors: [
    // joke / quotation
    "mazak",
    "mazaak",
    "majak",
    "mazak me",
    "mazaak me",
    "joke",
    "jokes",
    "just kidding",
    "kidding",
    // "don't (do/say) …" imperative — the "suicide jokes mat karo" family
    "mat karo",
    "mat kar",
    "mat bol",
    "mat kaho",
    "mat likho",
    // explicit reassurance
    "theek hoon",
    "thik hoon",
    "theek hu",
    "thik hu",
    "main theek",
    "mai theek",
    "sab theek",
    "bilkul theek",
    "fine hoon",
    "fine hu",
    "ok hoon",
    "sab badhiya",
    // topical / discussion-about
    "prevention",
    "essay",
    "news me",
    "khabar",
    "poster",
    "seminar",
    "awareness",
  ],
};
