/**
 * `pnpm sukoon:upload-audio [--dry-run]` — uploads the first-party audio set
 * (generated by scripts/sukoon-audio/generate.py) into the private sukoon-audio
 * Storage bucket, and points the three soundscape catalog rows at their files.
 *
 * WHAT GOES WHERE (matches the app's existing wiring — see services/exercises.ts):
 *   • ambient beds  -> ambient/<id>.mp3      (mixer's real-file-with-synth fallback)
 *   • soundscapes   -> meditations/<name>.mp3 + sukoon_exercises.audio_hi/en set
 *                      (language-neutral instrumental => same file for hi & en)
 * The tiny start/end chime + breath cues are NOT here — they ship bundled in
 * apps/web/public/sukoon/audio and are SW-precached (they must play instantly).
 *
 * Idempotent: re-running re-uploads (upsert) and re-points the same rows. Run
 * once after generate.py (or after dropping in professionally-licensed library
 * files at the same build/ paths). Reads the service-role client from the shared
 * lib (SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY in apps/api/.env).
 */
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { supabase } from "../src/lib/supabase.js";
import { SUKOON_AUDIO_BUCKET } from "../src/sukoon/lib/storage.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const BUILD = path.join(HERE, "sukoon-audio", "build");

/** local file under build/  ->  object path in the bucket */
const UPLOADS: { local: string; remote: string }[] = [
  { local: "bucket/ambient/rain.mp3", remote: "ambient/rain.mp3" },
  { local: "bucket/ambient/fan.mp3", remote: "ambient/fan.mp3" },
  { local: "bucket/ambient/crickets.mp3", remote: "ambient/crickets.mp3" },
  { local: "bucket/ambient/tanpura.mp3", remote: "ambient/tanpura.mp3" },
  { local: "bucket/meditations/deep-calm.mp3", remote: "meditations/deep-calm.mp3" },
  { local: "bucket/meditations/morning-light.mp3", remote: "meditations/morning-light.mp3" },
  { local: "bucket/meditations/ocean-drift.mp3", remote: "meditations/ocean-drift.mp3" },
];

/** soundscape row `key` -> the bucket object it should play (same file both langs) */
const SOUNDSCAPE_AUDIO: Record<string, string> = {
  sound_deep_calm: "meditations/deep-calm.mp3",
  sound_morning_light: "meditations/morning-light.mp3",
  sound_ocean_drift: "meditations/ocean-drift.mp3",
};

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const db = supabase();
  const store = db.storage.from(SUKOON_AUDIO_BUCKET);

  console.log(`sukoon:upload-audio${dryRun ? " [dry-run]" : ""} -> bucket ${SUKOON_AUDIO_BUCKET}`);

  for (const { local, remote } of UPLOADS) {
    const buf = await readFile(path.join(BUILD, local)); // throws loudly if generate.py hasn't run
    if (dryRun) {
      console.log(`  would upload ${remote.padEnd(30)} ${(buf.length / 1024).toFixed(1)} KB`);
      continue;
    }
    const { error } = await store.upload(remote, buf, { contentType: "audio/mpeg", upsert: true });
    if (error) throw new Error(`upload ${remote} failed: ${error.message}`);
    console.log(`  uploaded ${remote.padEnd(30)} ${(buf.length / 1024).toFixed(1)} KB`);
  }

  for (const [key, remote] of Object.entries(SOUNDSCAPE_AUDIO)) {
    if (dryRun) {
      console.log(`  would point ${key} -> ${remote} (audio_hi + audio_en)`);
      continue;
    }
    const { data, error } = await db
      .from("sukoon_exercises")
      .update({ audio_hi: remote, audio_en: remote })
      .eq("key", key)
      .select("id")
      .maybeSingle();
    if (error) throw new Error(`point ${key} failed: ${error.message}`);
    if (!data) throw new Error(`no sukoon_exercises row with key=${key} — run migration 0095 first`);
    console.log(`  pointed  ${key.padEnd(24)} -> ${remote}`);
  }

  console.log("done.");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("sukoon:upload-audio failed:", err instanceof Error ? err.stack : err);
    process.exit(1);
  });
