-- 0038_notes.sql
-- AI-generated, grounded, bilingual STUDY NOTES — one note per syllabus node.
--
-- A note is our-own-words study material for a topic: an overview, cited
-- key facts, a UP-specific angle, a PYQ-weightage analysis, mnemonics, a
-- quick-revision list, and further-reading links — all bilingual {hi,en}.
-- Notes are generated by apps/api/src/notes/ (RAG over our bank + CA + the
-- Anthropic web_search tool for current facts), critic-checked, and land as
-- `needs_review` in the Review Queue's Notes tab before a human publishes.
--
-- The publish gate mirrors the questions-table pattern: a note may only be
-- `published` when BOTH languages of its overview are present (i18n_complete),
-- enforced here by a trigger AND by lib/note-visibility.ts in code.
--
-- embedding_source_type already carries 'note' (migration 0002), so a published
-- note's content is embedded into `embeddings` by notes:embed with no enum change.

-- ---------------------------------------------------------------------------
-- note_status enum + notes table
-- ---------------------------------------------------------------------------
create type note_status as enum ('draft', 'needs_review', 'published');

create table public.notes (
  id               uuid primary key default gen_random_uuid(),
  -- One note per topic. CASCADE so deleting a node cleans up its note.
  syllabus_node_id uuid not null unique references public.syllabus_nodes(id) on delete cascade,

  -- Structured, bilingual note body. Shape (validated by zod at the API layer,
  -- packages/shared/src/notes.ts noteContentI18nSchema):
  --   { hi: NoteBody, en: NoteBody } where NoteBody = {
  --     overview: string,
  --     key_facts: [{ fact: string, source_ref: string|null }],
  --     up_angle: string,
  --     pyq_analysis: string,
  --     mnemonics: string[],
  --     quick_revision: string[],
  --     further_reading: [{ title: string, url: string }]
  --   }
  content_i18n     jsonb not null default '{}'::jsonb,

  -- Every externally-sourced fact carries a source_ref that resolves into this
  -- list: [{ id: string, title: string, url: string }] — the web_search /
  -- cited sources used during generation. Rendered as "Sources" + links out.
  sources          jsonb not null default '[]'::jsonb,

  -- Auto-derived SRS-card candidates from key_facts (6-10), STORED but never
  -- auto-added — offered as a one-tap "add this note's deck".
  --   [{ front_i18n: {hi,en}, back_i18n: {hi,en} }]
  srs_candidates   jsonb not null default '[]'::jsonb,

  status           note_status not null default 'draft',
  -- Bumped on every regeneration/human edit; pairs with (node) for provenance.
  version          int not null default 1,
  -- Generation audit: model id, prompt version, critic verdict, weightage snapshot,
  -- source_context_ids, web_search_used, machine_translated, etc.
  meta             jsonb not null default '{}'::jsonb,
  model            text,
  cost_usd         numeric not null default 0,

  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

comment on table public.notes is
  'AI-generated bilingual study notes, one per syllabus node. Our own words, grounded + cited. status=published only when the bilingual overview gate passes (trigger below + lib/note-visibility.ts).';
comment on column public.notes.content_i18n is
  'Structured bilingual body: { hi:NoteBody, en:NoteBody }. Validated by zod (noteContentI18nSchema).';
comment on column public.notes.srs_candidates is
  'Stored SRS-card candidates derived from key_facts; offered as one-tap "add this note deck", never auto-added.';

-- updated_at maintenance (shared trigger from 0002).
create trigger notes_set_updated_at
  before update on public.notes
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Publish gate — a note may only be `published` when BOTH languages of its
-- overview are non-blank. content_i18n -> '<locale>' -> 'overview'.
-- ---------------------------------------------------------------------------
create or replace function public.note_overview_i18n(content jsonb)
returns jsonb
language sql
immutable
as $$
  select jsonb_build_object(
    'hi', coalesce(content -> 'hi' ->> 'overview', ''),
    'en', coalesce(content -> 'en' ->> 'overview', '')
  );
$$;

create or replace function public.notes_publish_gate()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'published'
     and not public.i18n_complete(public.note_overview_i18n(new.content_i18n)) then
    raise exception 'note %: cannot publish without a bilingual overview (hi+en)', new.id
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

create trigger notes_publish_gate_trg
  before insert or update on public.notes
  for each row execute function public.notes_publish_gate();

-- ---------------------------------------------------------------------------
-- Indexes — the Review Queue hot path (needs_review, newest first) and the
-- reader's per-node lookup (already covered by the unique index on node id).
-- ---------------------------------------------------------------------------
create index notes_status_idx
  on public.notes (status, updated_at desc);
create index notes_needs_review_idx
  on public.notes (created_at desc)
  where status = 'needs_review';

-- ---------------------------------------------------------------------------
-- Dev-permissive RLS — same "REPLACED IN AUTH PHASE" pattern as 0013.
-- ---------------------------------------------------------------------------
alter table public.notes enable row level security;

create policy notes_dev_all on public.notes
  for all to anon, authenticated, service_role
  using (true) with check (true);
